pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'Java'
        // git 'Git'
    }

    stages {
        stage('Checkout') {
            steps {
                echo '📥 Getting code...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo '🔨 Building...'
                dir('user-service') {  // Change to user-service directory
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Testing...'
                dir('user-service') {  // Change to user-service directory
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                echo '📦 Creating JAR...'
                dir('user-service') {  // Change to user-service directory
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Success in Docker!'
            archiveArtifacts 'user-service/target/*.jar'
        }
        failure {
            echo '❌ Failed!'
        }
    }
}
